#ifndef _SYSCALLS_TABLE_X86_64_
#define _SYSCALLS_TABLE_X86_64_
#include "sandbox.h"

Syscall_abstract syscalls_table[] = {
	{0  , "read"                   , { UINT_32_TYPE, STRING_TYPE , UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{1  , "write"                  , { UINT_32_TYPE, STRING_TYPE , UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{2  , "open"                   , { STRING_TYPE , INT_32_TYPE , UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{3  , "close"                  , { UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{4  , "newstat"                , { STRING_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{5  , "newfstat"               , { UINT_32_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{6  , "newlstat"               , { STRING_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{7  , "poll"                   , { ADDRESS_TYPE, UINT_32_TYPE, INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{8  , "lseek"                  , { UINT_32_TYPE, INT_64_TYPE , UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{9  , "mmap"                   , { UINT_64_TYPE, UINT_64_TYPE, UINT_64_TYPE, UINT_64_TYPE, UINT_64_TYPE, UINT_64_TYPE }, NULL, NONE_ACTION},
	{10 , "mprotect"               , { UINT_64_TYPE, UINT_64_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{11 , "munmap"                 , { UINT_64_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{12 , "brk"                    , { UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{13 , "rt_sigaction"           , { INT_32_TYPE , ADDRESS_TYPE, ADDRESS_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{14 , "rt_sigprocmask"         , { INT_32_TYPE , ADDRESS_TYPE, ADDRESS_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{15 , "rt_sigreturn"           , { ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{16 , "ioctl"                  , { UINT_32_TYPE, UINT_32_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{17 , "pread64"                , { UINT_32_TYPE, STRING_TYPE , UINT_64_TYPE, INT_64_TYPE , ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{18 , "pwrite64"               , { UINT_32_TYPE, STRING_TYPE , UINT_64_TYPE, INT_64_TYPE , ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{19 , "readv"                  , { UINT_64_TYPE, ADDRESS_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{20 , "writev"                 , { UINT_64_TYPE, ADDRESS_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{21 , "access"                 , { STRING_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{22 , "pipe"                   , { ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{23 , "select"                 , { INT_32_TYPE , ADDRESS_TYPE, ADDRESS_TYPE, ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{24 , "sched_yield"            , { ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{25 , "mremap"                 , { UINT_64_TYPE, UINT_64_TYPE, UINT_64_TYPE, UINT_64_TYPE, UINT_64_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{26 , "msync"                  , { UINT_64_TYPE, UINT_64_TYPE, INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{27 , "mincore"                , { UINT_64_TYPE, UINT_64_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{28 , "madvise"                , { UINT_64_TYPE, UINT_64_TYPE, INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{29 , "shmget"                 , { INT_32_TYPE , UINT_64_TYPE, INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{30 , "shmat"                  , { INT_32_TYPE , STRING_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{31 , "shmctl"                 , { INT_32_TYPE , INT_32_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{32 , "dup"                    , { UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{33 , "dup2"                   , { UINT_32_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{34 , "pause"                  , { ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{35 , "nanosleep"              , { ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{36 , "getitimer"              , { INT_32_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{37 , "alarm"                  , { UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{38 , "setitimer"              , { INT_32_TYPE , ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{39 , "getpid"                 , { ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{40 , "sendfile64"             , { INT_32_TYPE , INT_32_TYPE , ADDRESS_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{41 , "socket"                 , { INT_32_TYPE , INT_32_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{42 , "connect"                , { INT_32_TYPE , ADDRESS_TYPE, INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{43 , "accept"                 , { INT_32_TYPE , ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{44 , "sendto"                 , { INT_32_TYPE , ADDRESS_TYPE, UINT_64_TYPE, UINT_32_TYPE, ADDRESS_TYPE, INT_32_TYPE  }, NULL, NONE_ACTION},
	{45 , "recvfrom"               , { INT_32_TYPE , ADDRESS_TYPE, UINT_64_TYPE, UINT_32_TYPE, ADDRESS_TYPE, ADDRESS_TYPE }, NULL, NONE_ACTION},
	{46 , "sendmsg"                , { INT_32_TYPE , ADDRESS_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{47 , "recvmsg"                , { INT_32_TYPE , ADDRESS_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{48 , "shutdown"               , { INT_32_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{49 , "bind"                   , { INT_32_TYPE , ADDRESS_TYPE, INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{50 , "listen"                 , { INT_32_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{51 , "getsockname"            , { INT_32_TYPE , ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{52 , "getpeername"            , { INT_32_TYPE , ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{53 , "socketpair"             , { INT_32_TYPE , INT_32_TYPE , INT_32_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{54 , "setsockopt"             , { INT_32_TYPE , INT_32_TYPE , INT_32_TYPE , STRING_TYPE , INT_32_TYPE , ___NONE_TYPE }, NULL, NONE_ACTION},
	{55 , "getsockopt"             , { INT_32_TYPE , INT_32_TYPE , INT_32_TYPE , STRING_TYPE , ADDRESS_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{56 , "clone"                  , { UINT_64_TYPE, UINT_64_TYPE, ADDRESS_TYPE, ADDRESS_TYPE, UINT_64_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{57 , "fork"                   , { ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{58 , "vfork"                  , { ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{59 , "execve"                 , { STRING_TYPE , ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{60 , "exit"                   , { INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{61 , "wait4"                  , { INT_32_TYPE , ADDRESS_TYPE, INT_32_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{62 , "kill"                   , { INT_32_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{63 , "newuname"               , { ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{64 , "semget"                 , { INT_32_TYPE , INT_32_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{65 , "semop"                  , { INT_32_TYPE , ADDRESS_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{66 , "semctl"                 , { INT_32_TYPE , INT_32_TYPE , INT_32_TYPE , UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{67 , "shmdt"                  , { STRING_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{68 , "msgget"                 , { INT_32_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{69 , "msgsnd"                 , { INT_32_TYPE , ADDRESS_TYPE, UINT_64_TYPE, INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{70 , "msgrcv"                 , { INT_32_TYPE , ADDRESS_TYPE, UINT_64_TYPE, INT_64_TYPE , INT_32_TYPE , ___NONE_TYPE }, NULL, NONE_ACTION},
	{71 , "msgctl"                 , { INT_32_TYPE , INT_32_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{72 , "fcntl"                  , { UINT_32_TYPE, UINT_32_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{73 , "flock"                  , { UINT_32_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{74 , "fsync"                  , { UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{75 , "fdatasync"              , { UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{76 , "truncate"               , { STRING_TYPE , INT_64_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{77 , "ftruncate"              , { UINT_32_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{78 , "getdents"               , { UINT_32_TYPE, ADDRESS_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{79 , "getcwd"                 , { STRING_TYPE , UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{80 , "chdir"                  , { STRING_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{81 , "fchdir"                 , { UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{82 , "rename"                 , { STRING_TYPE , STRING_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{83 , "mkdir"                  , { STRING_TYPE , UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{84 , "rmdir"                  , { STRING_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{85 , "creat"                  , { STRING_TYPE , UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{86 , "link"                   , { STRING_TYPE , STRING_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{87 , "unlink"                 , { STRING_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{88 , "symlink"                , { STRING_TYPE , STRING_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{89 , "readlink"               , { STRING_TYPE , STRING_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{90 , "chmod"                  , { STRING_TYPE , UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{91 , "fchmod"                 , { UINT_32_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{92 , "chown"                  , { STRING_TYPE , UINT_32_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{93 , "fchown"                 , { UINT_32_TYPE, UINT_32_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{94 , "lchown"                 , { STRING_TYPE , UINT_32_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{95 , "umask"                  , { INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{96 , "gettimeofday"           , { ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{97 , "getrlimit"              , { UINT_32_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{98 , "getrusage"              , { INT_32_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{99 , "sysinfo"                , { ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{100, "times"                  , { ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{101, "ptrace"                 , { INT_64_TYPE , INT_64_TYPE , UINT_64_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{102, "getuid"                 , { ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{103, "syslog"                 , { INT_32_TYPE , STRING_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{104, "getgid"                 , { ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{105, "setuid"                 , { UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{106, "setgid"                 , { UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{107, "geteuid"                , { ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{108, "getegid"                , { ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{109, "setpgid"                , { INT_32_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{110, "getppid"                , { ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{111, "getpgrp"                , { ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{112, "setsid"                 , { ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{113, "setreuid"               , { UINT_32_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{114, "setregid"               , { UINT_32_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{115, "getgroups"              , { INT_32_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{116, "setgroups"              , { INT_32_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{117, "setresuid"              , { UINT_32_TYPE, UINT_32_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{118, "getresuid"              , { ADDRESS_TYPE, ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{119, "setresgid"              , { UINT_32_TYPE, UINT_32_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{120, "getresgid"              , { ADDRESS_TYPE, ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{121, "getpgid"                , { INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{122, "setfsuid"               , { UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{123, "setfsgid"               , { UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{124, "getsid"                 , { INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{125, "capget"                 , { ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{126, "capset"                 , { ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{127, "rt_sigpending"          , { ADDRESS_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{128, "rt_sigtimedwait"        , { ADDRESS_TYPE, ADDRESS_TYPE, ADDRESS_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{129, "rt_sigqueueinfo"        , { INT_32_TYPE , INT_32_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{130, "rt_sigsuspend"          , { ADDRESS_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{131, "sigaltstack"            , { ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{132, "utime"                  , { STRING_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{133, "mknod"                  , { STRING_TYPE , UINT_32_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	EMPTY_SYSCALL,
	{135, "personality"            , { UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{136, "ustat"                  , { UINT_32_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{137, "statfs"                 , { STRING_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{138, "fstatfs"                , { UINT_32_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{139, "sysfs"                  , { INT_32_TYPE , UINT_64_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{140, "getpriority"            , { INT_32_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{141, "setpriority"            , { INT_32_TYPE , INT_32_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{142, "sched_setparam"         , { INT_32_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{143, "sched_getparam"         , { INT_32_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{144, "sched_setscheduler"     , { INT_32_TYPE , INT_32_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{145, "sched_getscheduler"     , { INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{146, "sched_get_priority_max" , { INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{147, "sched_get_priority_min" , { INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{148, "sched_rr_get_interval"  , { INT_32_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{149, "mlock"                  , { UINT_64_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{150, "munlock"                , { UINT_64_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{151, "mlockall"               , { INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{152, "munlockall"             , { ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{153, "vhangup"                , { ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{154, "modify_ldt"             , { INT_32_TYPE , ADDRESS_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{155, "pivot_root"             , { STRING_TYPE , STRING_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	EMPTY_SYSCALL,
	{157, "prctl"                  , { INT_32_TYPE , UINT_64_TYPE, UINT_64_TYPE, UINT_64_TYPE, UINT_64_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{158, "arch_prctl"             , { INT_32_TYPE , UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{159, "adjtimex"               , { ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{160, "setrlimit"              , { UINT_32_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{161, "chroot"                 , { STRING_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{162, "sync"                   , { ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{163, "acct"                   , { STRING_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{164, "settimeofday"           , { ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{165, "mount"                  , { STRING_TYPE , STRING_TYPE , STRING_TYPE , UINT_64_TYPE, ADDRESS_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{166, "umount"                 , { STRING_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{167, "swapon"                 , { STRING_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{168, "swapoff"                , { STRING_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{169, "reboot"                 , { INT_32_TYPE , INT_32_TYPE , UINT_32_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{170, "sethostname"            , { STRING_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{171, "setdomainname"          , { STRING_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{172, "iopl"                   , { UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{173, "ioperm"                 , { UINT_64_TYPE, UINT_64_TYPE, INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	EMPTY_SYSCALL,
	{175, "init_module"            , { ADDRESS_TYPE, UINT_64_TYPE, STRING_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{176, "delete_module"          , { STRING_TYPE , UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	{179, "quotactl"               , { UINT_32_TYPE, STRING_TYPE , UINT_32_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	{186, "gettid"                 , { ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{187, "readahead"              , { INT_32_TYPE , INT_64_TYPE , UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{188, "setxattr"               , { STRING_TYPE , STRING_TYPE , ADDRESS_TYPE, UINT_64_TYPE, INT_32_TYPE , ___NONE_TYPE }, NULL, NONE_ACTION},
	{189, "lsetxattr"              , { STRING_TYPE , STRING_TYPE , ADDRESS_TYPE, UINT_64_TYPE, INT_32_TYPE , ___NONE_TYPE }, NULL, NONE_ACTION},
	{190, "fsetxattr"              , { INT_32_TYPE , STRING_TYPE , ADDRESS_TYPE, UINT_64_TYPE, INT_32_TYPE , ___NONE_TYPE }, NULL, NONE_ACTION},
	{191, "getxattr"               , { STRING_TYPE , STRING_TYPE , ADDRESS_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{192, "lgetxattr"              , { STRING_TYPE , STRING_TYPE , ADDRESS_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{193, "fgetxattr"              , { INT_32_TYPE , STRING_TYPE , ADDRESS_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{194, "listxattr"              , { STRING_TYPE , STRING_TYPE , UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{195, "llistxattr"             , { STRING_TYPE , STRING_TYPE , UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{196, "flistxattr"             , { INT_32_TYPE , STRING_TYPE , UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{197, "removexattr"            , { STRING_TYPE , STRING_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{198, "lremovexattr"           , { STRING_TYPE , STRING_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{199, "fremovexattr"           , { INT_32_TYPE , STRING_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{200, "tkill"                  , { INT_32_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{201, "time"                   , { ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{202, "futex"                  , { ADDRESS_TYPE, INT_32_TYPE , UINT_32_TYPE, ADDRESS_TYPE, ADDRESS_TYPE, UINT_32_TYPE }, NULL, NONE_ACTION},
	{203, "sched_setaffinity"      , { INT_32_TYPE , UINT_32_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{204, "sched_getaffinity"      , { INT_32_TYPE , UINT_32_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	EMPTY_SYSCALL,
	{206, "io_setup"               , { UINT_32_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{207, "io_destroy"             , { UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{208, "io_getevents"           , { UINT_64_TYPE, INT_64_TYPE , INT_64_TYPE , ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{209, "io_submit"              , { UINT_64_TYPE, INT_64_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{210, "io_cancel"              , { UINT_64_TYPE, ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	{213, "epoll_create"           , { INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	{216, "remap_file_pages"       , { UINT_64_TYPE, UINT_64_TYPE, UINT_64_TYPE, UINT_64_TYPE, UINT_64_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{217, "getdents64"             , { UINT_32_TYPE, ADDRESS_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{218, "set_tid_address"        , { ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{219, "restart_syscall"        , { ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{220, "semtimedop"             , { INT_32_TYPE , ADDRESS_TYPE, UINT_32_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{221, "fadvise64"              , { INT_32_TYPE , INT_64_TYPE , UINT_64_TYPE, INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{222, "timer_create"           , { INT_32_TYPE , ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{223, "timer_settime"          , { ADDRESS_TYPE, INT_32_TYPE , ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{224, "timer_gettime"          , { ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{225, "timer_getoverrun"       , { ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{226, "timer_delete"           , { ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{227, "clock_settime"          , { INT_32_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{228, "clock_gettime"          , { INT_32_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{229, "clock_getres"           , { INT_32_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{230, "clock_nanosleep"        , { INT_32_TYPE , INT_32_TYPE , ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{231, "exit_group"             , { INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{232, "epoll_wait"             , { INT_32_TYPE , ADDRESS_TYPE, INT_32_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{233, "epoll_ctl"              , { INT_32_TYPE , INT_32_TYPE , INT_32_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{234, "tgkill"                 , { INT_32_TYPE , INT_32_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{235, "utimes"                 , { STRING_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	EMPTY_SYSCALL,
	{237, "mbind"                  , { UINT_64_TYPE, UINT_64_TYPE, UINT_64_TYPE, ADDRESS_TYPE, UINT_64_TYPE, UINT_32_TYPE }, NULL, NONE_ACTION},
	{238, "set_mempolicy"          , { INT_32_TYPE , ADDRESS_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{239, "get_mempolicy"          , { ADDRESS_TYPE, ADDRESS_TYPE, UINT_64_TYPE, UINT_64_TYPE, UINT_64_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{240, "mq_open"                , { STRING_TYPE , INT_32_TYPE , UINT_32_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{241, "mq_unlink"              , { STRING_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{242, "mq_timedsend"           , { INT_32_TYPE , STRING_TYPE , UINT_64_TYPE, UINT_32_TYPE, ADDRESS_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{243, "mq_timedreceive"        , { INT_32_TYPE , STRING_TYPE , UINT_64_TYPE, ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{244, "mq_notify"              , { INT_32_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{245, "mq_getsetattr"          , { INT_32_TYPE , ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{246, "kexec_load"             , { UINT_64_TYPE, UINT_64_TYPE, ADDRESS_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{247, "waitid"                 , { INT_32_TYPE , INT_32_TYPE , ADDRESS_TYPE, INT_32_TYPE , ADDRESS_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{248, "add_key"                , { STRING_TYPE , STRING_TYPE , ADDRESS_TYPE, UINT_64_TYPE, INT_32_TYPE , ___NONE_TYPE }, NULL, NONE_ACTION},
	{249, "request_key"            , { STRING_TYPE , STRING_TYPE , STRING_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{250, "keyctl"                 , { INT_32_TYPE , UINT_64_TYPE, UINT_64_TYPE, UINT_64_TYPE, UINT_64_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{251, "ioprio_set"             , { INT_32_TYPE , INT_32_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{252, "ioprio_get"             , { INT_32_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{253, "inotify_init"           , { ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{254, "inotify_add_watch"      , { INT_32_TYPE , STRING_TYPE , UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{255, "inotify_rm_watch"       , { INT_32_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{256, "migrate_pages"          , { INT_32_TYPE , UINT_64_TYPE, ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{257, "openat"                 , { INT_32_TYPE , STRING_TYPE , INT_32_TYPE , UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{258, "mkdirat"                , { INT_32_TYPE , STRING_TYPE , UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{259, "mknodat"                , { INT_32_TYPE , STRING_TYPE , UINT_32_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{260, "fchownat"               , { INT_32_TYPE , STRING_TYPE , UINT_32_TYPE, UINT_32_TYPE, INT_32_TYPE , ___NONE_TYPE }, NULL, NONE_ACTION},
	{261, "futimesat"              , { INT_32_TYPE , STRING_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{262, "newfstatat"             , { INT_32_TYPE , STRING_TYPE , ADDRESS_TYPE, INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{263, "unlinkat"               , { INT_32_TYPE , STRING_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{264, "renameat"               , { INT_32_TYPE , STRING_TYPE , INT_32_TYPE , STRING_TYPE , ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{265, "linkat"                 , { INT_32_TYPE , STRING_TYPE , INT_32_TYPE , STRING_TYPE , INT_32_TYPE , ___NONE_TYPE }, NULL, NONE_ACTION},
	{266, "symlinkat"              , { STRING_TYPE , INT_32_TYPE , STRING_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{267, "readlinkat"             , { INT_32_TYPE , STRING_TYPE , STRING_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{268, "fchmodat"               , { INT_32_TYPE , STRING_TYPE , UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{269, "faccessat"              , { INT_32_TYPE , STRING_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{270, "pselect6"               , { INT_32_TYPE , ADDRESS_TYPE, ADDRESS_TYPE, ADDRESS_TYPE, ADDRESS_TYPE, ADDRESS_TYPE }, NULL, NONE_ACTION},
	{271, "ppoll"                  , { ADDRESS_TYPE, UINT_32_TYPE, ADDRESS_TYPE, ADDRESS_TYPE, UINT_64_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{272, "unshare"                , { UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{273, "set_robust_list"        , { ADDRESS_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{274, "get_robust_list"        , { INT_32_TYPE , ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{275, "splice"                 , { INT_32_TYPE , ADDRESS_TYPE, INT_32_TYPE , ADDRESS_TYPE, UINT_64_TYPE, UINT_32_TYPE }, NULL, NONE_ACTION},
	{276, "tee"                    , { INT_32_TYPE , INT_32_TYPE , UINT_64_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{277, "sync_file_range"        , { INT_32_TYPE , INT_64_TYPE , INT_64_TYPE , UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{278, "vmsplice"               , { INT_32_TYPE , ADDRESS_TYPE, UINT_64_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{279, "move_pages"             , { INT_32_TYPE , UINT_64_TYPE, ADDRESS_TYPE, ADDRESS_TYPE, ADDRESS_TYPE, INT_32_TYPE  }, NULL, NONE_ACTION},
	{280, "utimensat"              , { INT_32_TYPE , STRING_TYPE , ADDRESS_TYPE, INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{281, "epoll_pwait"            , { INT_32_TYPE , ADDRESS_TYPE, INT_32_TYPE , INT_32_TYPE , ADDRESS_TYPE, UINT_64_TYPE }, NULL, NONE_ACTION},
	{282, "signalfd"               , { INT_32_TYPE , ADDRESS_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{283, "timerfd_create"         , { INT_32_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{284, "eventfd"                , { UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{285, "fallocate"              , { INT_32_TYPE , INT_32_TYPE , INT_64_TYPE , INT_64_TYPE , ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{286, "timerfd_settime"        , { INT_32_TYPE , INT_32_TYPE , ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{287, "timerfd_gettime"        , { INT_32_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{288, "accept4"                , { INT_32_TYPE , ADDRESS_TYPE, ADDRESS_TYPE, INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{289, "signalfd4"              , { INT_32_TYPE , ADDRESS_TYPE, UINT_64_TYPE, INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{290, "eventfd2"               , { UINT_32_TYPE, INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{291, "epoll_create1"          , { INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{292, "dup3"                   , { UINT_32_TYPE, UINT_32_TYPE, INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{293, "pipe2"                  , { ADDRESS_TYPE, INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{294, "inotify_init1"          , { INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{295, "preadv"                 , { UINT_64_TYPE, ADDRESS_TYPE, UINT_64_TYPE, UINT_64_TYPE, UINT_64_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{296, "pwritev"                , { UINT_64_TYPE, ADDRESS_TYPE, UINT_64_TYPE, UINT_64_TYPE, UINT_64_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{297, "rt_tgsigqueueinfo"      , { INT_32_TYPE , INT_32_TYPE , INT_32_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{298, "perf_event_open"        , { ADDRESS_TYPE, INT_32_TYPE , INT_32_TYPE , INT_32_TYPE , UINT_64_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{299, "recvmmsg"               , { INT_32_TYPE , ADDRESS_TYPE, UINT_32_TYPE, UINT_32_TYPE, ADDRESS_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{300, "fanotify_init"          , { UINT_32_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{301, "fanotify_mark"          , { INT_32_TYPE , UINT_32_TYPE, UINT_64_TYPE, INT_32_TYPE , STRING_TYPE , ___NONE_TYPE }, NULL, NONE_ACTION},
	{302, "prlimit64"              , { INT_32_TYPE , UINT_32_TYPE, ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{303, "name_to_handle_at"      , { INT_32_TYPE , STRING_TYPE , ADDRESS_TYPE, ADDRESS_TYPE, INT_32_TYPE , ___NONE_TYPE }, NULL, NONE_ACTION},
	{304, "open_by_handle_at"      , { INT_32_TYPE , ADDRESS_TYPE, INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{305, "clock_adjtime"          , { INT_32_TYPE , ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{306, "syncfs"                 , { INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{307, "sendmmsg"               , { INT_32_TYPE , ADDRESS_TYPE, UINT_32_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{308, "setns"                  , { INT_32_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{309, "getcpu"                 , { ADDRESS_TYPE, ADDRESS_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{310, "process_vm_readv"       , { INT_32_TYPE , ADDRESS_TYPE, UINT_64_TYPE, ADDRESS_TYPE, UINT_64_TYPE, UINT_64_TYPE }, NULL, NONE_ACTION},
	{311, "process_vm_writev"      , { INT_32_TYPE , ADDRESS_TYPE, UINT_64_TYPE, ADDRESS_TYPE, UINT_64_TYPE, UINT_64_TYPE }, NULL, NONE_ACTION},
	{312, "kcmp"                   , { INT_32_TYPE , INT_32_TYPE , INT_32_TYPE , UINT_64_TYPE, UINT_64_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{313, "finit_module"           , { INT_32_TYPE , STRING_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{314, "sched_setattr"          , { INT_32_TYPE , ADDRESS_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{315, "sched_getattr"          , { INT_32_TYPE , ADDRESS_TYPE, UINT_32_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{316, "renameat2"              , { INT_32_TYPE , STRING_TYPE , INT_32_TYPE , STRING_TYPE , UINT_32_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{317, "seccomp"                , { UINT_32_TYPE, UINT_32_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{318, "getrandom"              , { STRING_TYPE , UINT_64_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{319, "memfd_create"           , { STRING_TYPE , UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{320, "kexec_file_load"        , { INT_32_TYPE , INT_32_TYPE , UINT_64_TYPE, STRING_TYPE , UINT_64_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{321, "bpf"                    , { INT_32_TYPE , ADDRESS_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{322, "execveat"               , { INT_32_TYPE , STRING_TYPE , ADDRESS_TYPE, ADDRESS_TYPE, INT_32_TYPE , ___NONE_TYPE }, NULL, NONE_ACTION},
	{323, "userfaultfd"            , { INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{324, "membarrier"             , { INT_32_TYPE , UINT_32_TYPE, INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{325, "mlock2"                 , { UINT_64_TYPE, UINT_64_TYPE, INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{326, "copy_file_range"        , { INT_32_TYPE , ADDRESS_TYPE, INT_32_TYPE , ADDRESS_TYPE, UINT_64_TYPE, UINT_32_TYPE }, NULL, NONE_ACTION},
	{327, "preadv2"                , { UINT_64_TYPE, ADDRESS_TYPE, UINT_64_TYPE, UINT_64_TYPE, UINT_64_TYPE, INT_32_TYPE  }, NULL, NONE_ACTION},
	{328, "pwritev2"               , { UINT_64_TYPE, ADDRESS_TYPE, UINT_64_TYPE, UINT_64_TYPE, UINT_64_TYPE, INT_32_TYPE  }, NULL, NONE_ACTION},
	{329, "pkey_mprotect"          , { UINT_64_TYPE, UINT_64_TYPE, UINT_64_TYPE, INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{330, "pkey_alloc"             , { UINT_64_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{331, "pkey_free"              , { INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{332, "statx"                  , { INT_32_TYPE , STRING_TYPE , UINT_32_TYPE, UINT_32_TYPE, ADDRESS_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{333, "io_pgetevents"          , { UINT_64_TYPE, INT_64_TYPE , INT_64_TYPE , ADDRESS_TYPE, ADDRESS_TYPE, ADDRESS_TYPE }, NULL, NONE_ACTION},
	{334, "rseq"                   , { ADDRESS_TYPE, UINT_32_TYPE, INT_32_TYPE , UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	EMPTY_SYSCALL,
	{424, "pidfd_send_signal"      , { INT_32_TYPE , INT_32_TYPE , ADDRESS_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{425, "io_uring_setup"         , { UINT_32_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{426, "io_uring_enter"         , { UINT_32_TYPE, UINT_32_TYPE, UINT_32_TYPE, UINT_32_TYPE, ADDRESS_TYPE, UINT_64_TYPE }, NULL, NONE_ACTION},
	{427, "io_uring_register"      , { UINT_32_TYPE, UINT_32_TYPE, ADDRESS_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{428, "open_tree"              , { INT_32_TYPE , STRING_TYPE , UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{429, "move_mount"             , { INT_32_TYPE , STRING_TYPE , INT_32_TYPE , STRING_TYPE , UINT_32_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{430, "fsopen"                 , { STRING_TYPE , UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{431, "fsconfig"               , { INT_32_TYPE , UINT_32_TYPE, STRING_TYPE , ADDRESS_TYPE, INT_32_TYPE , ___NONE_TYPE }, NULL, NONE_ACTION},
	{432, "fsmount"                , { INT_32_TYPE , UINT_32_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{433, "fspick"                 , { INT_32_TYPE , STRING_TYPE , UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{434, "pidfd_open"             , { INT_32_TYPE , UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{435, "clone3"                 , { ADDRESS_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{436, "close_range"            , { UINT_32_TYPE, UINT_32_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{437, "openat2"                , { INT_32_TYPE , STRING_TYPE , ADDRESS_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{438, "pidfd_getfd"            , { INT_32_TYPE , INT_32_TYPE , UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{439, "faccessat2"             , { INT_32_TYPE , STRING_TYPE , INT_32_TYPE , INT_32_TYPE , ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{440, "process_madvise"        , { INT_32_TYPE , ADDRESS_TYPE, UINT_64_TYPE, INT_32_TYPE , UINT_32_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{441, "epoll_pwait2"           , { INT_32_TYPE , ADDRESS_TYPE, INT_32_TYPE , ADDRESS_TYPE, ADDRESS_TYPE, UINT_64_TYPE }, NULL, NONE_ACTION},
	{442, "mount_setattr"          , { INT_32_TYPE , STRING_TYPE , UINT_32_TYPE, ADDRESS_TYPE, UINT_64_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{443, "quotactl_fd"            , { UINT_32_TYPE, UINT_32_TYPE, UINT_32_TYPE, ADDRESS_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{444, "landlock_create_ruleset", { ADDRESS_TYPE, UINT_64_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{445, "landlock_add_rule"      , { INT_32_TYPE , INT_32_TYPE , ADDRESS_TYPE, UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{446, "landlock_restrict_self" , { INT_32_TYPE , UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{447, "memfd_secret"           , { UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{448, "process_mrelease"       , { INT_32_TYPE , UINT_32_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION},
	{449, "futex_waitv"            , { ADDRESS_TYPE, UINT_32_TYPE, UINT_32_TYPE, ADDRESS_TYPE, INT_32_TYPE , ___NONE_TYPE }, NULL, NONE_ACTION},
	{450, "set_mempolicy_home_node", { UINT_64_TYPE, UINT_64_TYPE, UINT_64_TYPE, UINT_64_TYPE, ___NONE_TYPE, ___NONE_TYPE }, NULL, NONE_ACTION}
};

const size_t syscalls_table_len = sizeof(syscalls_table) / sizeof(syscalls_table[0]);
const u_int32_t NUMBER_OF_SYSCALLS = 345;//sizeof(Syscall_rules) / sizeof(char**);

#endif